spring:
  datasource:
    url: jdbc:sqlserver://backed-sdcc-server.database.windows.net:1433;databaseName=database;user=backed-sdcc-server-admin;password=3383WJO08775KZHZ$
    username: backed-sdcc-server-admin
    password: 3383WJO08775KZHZ$

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect


server:
  port: 8081
