spring:
  datasource:
    url: jdbc:sqlserver://10.0.0.4:1433;database=database-sdcc;user=amministratore@server-sdcc;password=Clarinetto.00;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: amministratore
    password: Clarinetto.00

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect


server:
  port: 8081
